debug: false # if true, only a subset of the data (100) is used to train

categories: ['structured', 'disordered']
filters: 150
kernel_size: 7
n_resnet: 1
lr: 1.0e-4
batch_size: 8 # Reduced batch size to prevent memory issues
nepoch: 500
patience: 10
win_len: 13
soft_max: true
pLM: 'ProtT5'
emb_size:
  ESM2: 1280
  ProtT5: 1024
  ProstT5: 1024

# [ ] Revisar estos parámetros y eliminar los innecesarios