debug: false # if true, only a subset of the data (100) is used to train
datasets_to_test: 
  - dev
  - test
  - disorder_nox
  - disorder_pdb

categories: ['structured', 'disordered']
filters: 400
kernel_size: 11
n_resnet: 2
lr: 0.00012774325937536552
batch_size: 16
nepoch: 500
patience: 10
win_len: 30
soft_max: true
p_dropout: 0.2
pLM: 'ESM2'
emb_size:
  ESM2: 1280
  ProtT5: 1024
  ProstT5: 1024
  esmc_300m: 960
  esmc_600m: 1152