batch_size: 16
categories:
- structured
- disordered
debug: false
emb_size:
  ESM2: 1280
  ProstT5: 1024
  ProtT5: 1024
  esmc_300m: 960
  esmc_600m: 1152
filters: 400
kernel_size: 11
lr: 0.00012774325937536552
n_resnet: 2
nepoch: 500
plm: ESM2
p_dropout: 0.2
patience: 10
soft_max: true
win_len: 30
